# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tool.cm-我的互联网工具箱
keywords: 在线工具,网址导航,创意导航,UI设计,设计素材,设计资源,设计师导航,产品经理网址导航,个人博客导航
description: Tool.cm - 收集国内外优秀设计网站、UI设计资源网站、灵感创意网站、素材资源网站以及优秀个人独立博客站，定时更新分享优质产品设计书签。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tool.cm" # the base hostname & protocol for your site, e.g. http://example.com

static:
  path:
    logo: /assets/images/logos/

email: 5151@88.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

github:
  repo: HenMeng/webstack-jekyll

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
