name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.Bucket }} # 这里格式是 bucket-appid
        AWS_ACCESS_KEY_ID: ${{ secrets.SecretId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SecretKey }}
        AWS_S3_ENDPOINT: 'https://cos.ap-chengdu.myqcloud.com' # 将ap-chengdu换成自己的地域
        SOURCE_DIR: tool
